# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MatFind <- function(A, ZeroThres) {
    .Call(`_QuickPNMFs_MatFind`, A, ZeroThres)
}

MatFindlb <- function(A, lb) {
    .Call(`_QuickPNMFs_MatFindlb`, A, lb)
}

SMatC <- function(X, clu) {
    .Call(`_QuickPNMFs_SMatC`, X, clu)
}

PNMF_EucDistC <- function(X, W_init, tol, maxIter, verboseN, zerotol) {
    .Call(`_QuickPNMFs_PNMF_EucDistC`, X, W_init, tol, maxIter, verboseN, zerotol)
}

PNMF_KLC <- function(X, W_init, tol, maxIter, verboseN, zerotol) {
    .Call(`_QuickPNMFs_PNMF_KLC`, X, W_init, tol, maxIter, verboseN, zerotol)
}

DPNMFC <- function(X, W_init, tol, maxIter, verboseN, zerotol, Xord, clunum, mu, lambda) {
    .Call(`_QuickPNMFs_DPNMFC`, X, W_init, tol, maxIter, verboseN, zerotol, Xord, clunum, mu, lambda)
}

